server:
  port: 8095

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:mysql://xe2dev.cnxocunlrmpk.us-east-2.rds.amazonaws.com:${SQL_PORT:1433};databaseName=${SQL_DB:xe2dev}; # for aws mysql db
    username: sa # for aws mysql db
    password: root1234 # for aws mysql db
    hikari: 
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
  application:
    name: product

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888 #link to cloud config server
      label: main #name of git repo branch
  profiles:
    active: product
     
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instanceId: ${spring.application.name}
  client:
    # Eureka Server URL
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true
      
